export const GET_PROPERTIES_SEARCH = "home/GET_PROPERTIES_SEARCH";
export const GET_PROPERTIES_FEATURED_LISTINGS =
  "home/GET_PROPERTIES_FEATURED_LISTINGS";
export const GET_PROPERTY_DETAILS = "property-details/GET_PROPERTY_DETAILS";
